config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#index"
  
  # Pages
  get "main" => "pages#main"
  get "instrucoes" => "pages#instrucoes"
  get "procedures" => "pages#procedures"
  get "opine" => "pages#opine"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :user_exams
  has_many :users, through: :user_exams

  validates :name, presence: true
  validates :video_url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :user_type, presence: true, inclusion: { in: %w[cpf cnpj] }
  validates :cpf, presence: true, if: -> { user_type == "cpf" }
  validates :cnpj, presence: true, if: -> { user_type == "cnpj" }
  validates :clinic_doctor, presence: true
  validates :phone, presence: true
  validates :name, presence: true

  has_many :user_exams
  has_many :exams, through: :user_exams
end

app/models/user_exam.rb
class UserExam < ApplicationRecord
  belongs_to :user
  belongs_to :exam

  validates :user_id, uniqueness: { scope: :exam_id, message: "já está associado a esse exame" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:clinic_doctor, :name, :user_type, :cpf, :cnpj, :phone])
    devise_parameter_sanitizer.permit(:account_update, keys: [:clinic_doctor, :name, :user_type, :cpf, :cnpj, :phone])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def main
  end

  def instrucoes
    render turbo_stream: turbo_stream.replace('active-screen', partial: 'pages/instrucoes')
  end

  def procedures
    render turbo_stream: turbo_stream.replace('active-screen', partial: 'pages/procedures')
  end

  def opine
    render turbo_stream: turbo_stream.replace('active-screen', partial: 'pages/opine')
  end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  def apresentacao
    render partial: 'procedures/apresentacao'
  end

  def pre_exame
    render partial: 'procedures/pre_exame'
  end

  def acuidade
    render partial: 'procedures/acuidade'
  end

  def biomicroscopia
    render partial: 'procedures/biomicroscopia'
  end

  def refracao
    render partial: 'procedures/refracao'
  end

  def tonometria
    render partial: 'procedures/tonometria'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/videos_helper.rb
# app/helpers/videos_helper.rb
module VideosHelper
    def youtube_embed(video_id, width: 560, height: 315)
        params = {
            rel: 0,
            modestbranding: 1,
            iv_load_policy: 3,
            disablekb: 1,
            origin: request.base_url,
            autohide: 1,       # Esconde controles automaticamente
            playsinline: 1      # Boas práticas para mobile
        }
        
        content_tag(:div, class: "youtube-wrapper") do
            content_tag(:iframe, nil, 
            src: "https://www.youtube-nocookie.com/embed/#{video_id}?#{params.to_query}",
            width: width,
            height: height,
            frameborder: "0",
            allow: "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture",
            allowfullscreen: true,
            loading: "lazy",
            class: "youtube-player"
            )
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IncluaMed</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_instrucoes.html.erb
<turbo-frame class="active-screen-default" id="active-screen">
  <div class="active-screen">
    <div class="main">

        <h1 class="comece"> Primeiros passos </h1>
        <p> Assista o video abaixo para descobrir como a Inclua pensou em você e pode te ajudar! </p>
        <%= youtube_embed("OTzYZ26Ilzw") %>
        
      </div>
</turbo-frame>

app/views/pages/_opine.html.erb
<turbo-frame class="active-screen-default" id="active-screen">
  <div class="active-screen">
    <div class="main">

        <h1 class="comece"> Nos ajude a melhorar!</h1>
        <p class="opine_h"> Sobre esta experiência </p>
        <p class="opine_p"> Este painel foi feito para fornecer um atendimento mais inclusivo. Queremos tornar cada vez mais essa experiência melhor. <br> O seu feedback é muito importante! <br> Opine abaixo livremente.  </p>
      
        <form onsubmit="return false;">

          <div class="form-group">
            <input type="text" id="opiniao" name="opiniao" required minlength="50">
          </div>  
          <button type="submit" class="submit-button"> Enviar Opinião </button>

        </form>        
        
      </div>
  </div>
  </div>
</turbo-frame>

app/views/pages/_procedures.html.erb
<turbo-frame class="active-screen-default" id="active-screen">
  <div class="active-screen">
    
      <div class="main">

        <h1 class="comece"> Procedimentos</h1>
        <p> Escolha o procedimento desejado: </p>
      
      </div>
  </div>
</turbo-frame>

app/views/pages/index.html.erb
<div class="wrapper" data-controller="menu">
    <div class="container">
        <div class="logo">
            <%= image_tag "logo.png" %>
        </div>        
        <%= link_to "<h1>COMEÇAR</h1>".html_safe, main_path, class: "no-underline" %>
    </div>
</div>

app/views/pages/main.html.erb
<div class="page">
  <%= render 'shared/navbar' %>

  <div class="mini-circle" id="fullscreen-button">
    <%= image_tag "fullscreen.svg", alt: "Tela Cheia", class: "seta-fullscreen" %>
  </div>
  
  <turbo-frame class="active-screen-default" id="active-screen">
    <div class="active-screen">

      <div class="main">

        <h1 class="comece"> Comece por aqui </h1>

        <p> Escolha um dos itens no menu ao lado para começar seu atendimento. </p>

      
      </div>

    </div>
  </turbo-frame>
</div>

app/views/procedures/_acuidade.html.erb
<turbo-frame class="active-screen-default" id="active-screen">
  <div class="active-screen">
    <div class="main">
      <h1 class="comece"> Acuidade visual </h1>
      <p> Teste de capacidade visual </p>

      <%= youtube_embed("xrr1z3Mi5PM") %>

      <%= link_to procedures_path, remote: true do %>
        <%= image_tag "purple-arrow-back", class: "purple-arrow-back" %>
      <% end %>
    </div>
  </div>
</turbo-frame>

app/views/procedures/_apresentacao.html.erb
<turbo-frame class="active-screen-default" id="active-screen">
  <div class="active-screen">
    
      <div class="main">

        <h1 class="comece"> Apresentação </h1>
        <p> Primeiro contato e anamnese </p>

        <%= youtube_embed("OTzYZ26Ilzw") %>

        <%= link_to procedures_path, remote: true do %>
          <%= image_tag "purple-arrow-back", class: "purple-arrow-back" %>
        <% end %>        
      
      </div>
  </div>
</turbo-frame>

app/views/procedures/_biomicroscopia.html.erb
<turbo-frame class="active-screen-default" id="active-screen">
  <div class="active-screen">
    
      <div class="main">

        <h1 class="comece"> Biomicroscopia </h1>
        <p> Análise estrutural ocular </p>

        <%= youtube_embed("Th5OdHNRj_4") %>
        
        <%= link_to procedures_path, remote: true do %>
          <%= image_tag "purple-arrow-back", class: "purple-arrow-back" %>
        <% end %>        
      
      </div>
  </div>
</turbo-frame>

app/views/procedures/_pre_exame.html.erb
<turbo-frame class="active-screen-default" id="active-screen">
  <div class="active-screen">
    
      <div class="main">

        <h1 class="comece"> Pré-exame </h1>
        <p> Preparação inicial do paciente </p>

        <%= youtube_embed("XbPz2cKTHSY") %>

        <%= link_to procedures_path, remote: true do %>
          <%= image_tag "purple-arrow-back", class: "purple-arrow-back" %>
        <% end %>
      
      </div>
  </div>
</turbo-frame>

app/views/procedures/_refracao.html.erb
<turbo-frame class="active-screen-default" id="active-screen">
  <div class="active-screen">
    
      <div class="main">

        <h1 class="comece"> Refração </h1>
        <p> Medição do grau óptico </p>

        <%= youtube_embed("5sldIaj4M08") %>

        <%= link_to procedures_path, remote: true do %>
          <%= image_tag "purple-arrow-back", class: "purple-arrow-back" %>
        <% end %>
      
      </div>
  </div>
</turbo-frame>

app/views/procedures/_tonometria.html.erb
<turbo-frame class="active-screen-default" id="active-screen">
  <div class="active-screen">
    
      <div class="main">

        <h1 class="comece"> Tonometria </h1>
        <p> Verificação da pressão intraocular </p>

        <%= youtube_embed("pjWcjMLh8Jk") %>

        <%= link_to procedures_path, remote: true do %>
          <%= image_tag "purple-arrow-back", class: "purple-arrow-back" %>
        <% end %>
      
      </div>
  </div>
</turbo-frame>

app/views/shared/_navbar.html.erb
<div data-controller="menu" data-menu-current-path="<%= request.path %>">
  <%= image_tag "logo-reduzida.png", class: "logo-reduzida hidden", data: { menu_target: "logoReduzida" } %> <!- -- LOGO REDUZIDA FORA DO MENU - ACIMA -->
  <div class="logo-reduzida-circle hidden" data-menu-target="logoReduzidaCircle"></div> <!- -- CIRCULO LOGO REDUZIDA FORA DO MENU - ACIMA -->

  <div data-menu-target="menu" class="menu">
    <div class="container-menu">
      <div class="upper-menu">
        <%= image_tag "logo.png", class: "logo-menu" %>
        <ul>
          <li>
            <%= link_to instrucoes_path, class: "links", data: {
              turbo_frame: "active-screen",
              "turbo-prefetch": "false",
              action: "click->menu#selectItem"
            } do %>
              <%= image_tag "icon-home.svg", class: "icon", data: {
                menu_target: "icon",
                icon_default: asset_path("icon-home.svg"),
                icon_selected: asset_path("icon-home-selected.svg")
              } %>
              <p class="menu-text" data-menu-target="menuText">Início</p>
            <% end %>
          </li>
          <li>
            <%= link_to procedures_path, class: "links", data: {
              turbo_frame: "active-screen",
              "turbo-prefetch": "false",
              action: "click->menu#selectItem"
            } do %>
              <%= image_tag "icon-procedures.svg", class: "icon", data: {
                menu_target: "icon",
                icon_default: asset_path("icon-procedures.svg"),
                icon_selected: asset_path("icon-procedures-selected.svg")
              } %>
              <p class="menu-text" data-menu-target="menuText">Procedimentos</p>
            <% end %>
          </li>
          <li>
            <%= link_to opine_path, class: "links", data: {
              turbo_frame: "active-screen",
              "turbo-prefetch": "false",
              action: "click->menu#selectItem"
            } do %>
              <%= image_tag "icon-opine.svg", class: "icon", data: {
                menu_target: "icon",
                icon_default: asset_path("icon-opine.svg"),
                icon_selected: asset_path("icon-opine-selected.svg")
              } %>
              <p class="menu-text" data-menu-target="menuText">Dê sua opinião!</p>
            <% end %>
          </li>
        </ul>
      </div>

      <div class="arrow-container">
        <%= image_tag "arrow-back", class: "arrow-back", data: {
          action: 'click->menu#animateMenu',
          menu_target: "arrow"
        } %>

        <%= image_tag "arrow-back", class: "arrow-forward hidden", data: {
          action: 'click->menu#animateMenu',
          menu_target: "arrowForward"
        } %>
      </div>

    </div>
  </div>
  <%= image_tag "menu-hamburger.svg", class: "menu-hamburger hidden", data: { menu_target: "hamburgerIcon", action: 'click->menu#animateReverseMenuToExpandedState' } %>
</div>